### ISSUE TITLE
Fatal  Error: imap.php Undefined constant ZPush::ASV_161

### ISSUE THREAD

**Issue by Helmut1965** [Z-Hub/Z-Push#109]
I installed the current version on debian bookworm. My log shows the following crash for:
imap.php at 1993:
 02/10/2024 14:41:07 [173797] [FATAL] [xxxxxx] Fatal error: /usr/share/z-push/backend/imap/imap.php:1993 - Uncaught Error: Undefined constant ZPush::ASV_161 in /usr/share/z-push/backend/imap/imap.php:1993
Stack trace:
#0 /usr/share/z-push/lib/core/zpush.php(835): BackendIMAP->GetSupportedASVersion()
#1 /usr/share/z-push/lib/core/zpush.php(849): ZPush::GetSupportedASVersion()
#2 /usr/share/z-push/index.php(93): ZPush::GetServerHeader()
#3 {main}
  thrown (1)
 In case I change line 1993 back to
return ZPush::ASV_14;

it works

**Comment by matidau** [comment]
Hi @Helmut1965, Can you check what is in your lib/core/zpush.php? There should be  constant for ASV_161 around line 49. 

Edit: based on #110 you are not using the latest dev branch. ActiveSynce 16.1 is only available from Dev and hasn't been released.

**Comment by Helmut1965** [comment]
can be closed, was caused by a version mix. Sorry for the effort
Helmut

**Comment by Helmut1965** [comment]
can be closed, was caused by a version mix. Sorry for the effort
Helmut
