### ISSUE TITLE
Fatal Error ipcsharedmemoryprovider.php:44

### ISSUE THREAD

**Issue by Helmut1965** [Z-Hub/Z-Push#110]
I installed the current version of Z-push, Debian Bookworm PHP 8.2
I face the following error:
02/10/2024 14:51:40 [174018] [FATAL] [XXXXXX] Fatal error: /usr/share/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php:44 - Uncaught Error: Object of class SysvSemaphore could not be converted to string in /usr/share/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php:44
Stack trace:
#0 /usr/share/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php(44): sprintf()
#1 /usr/share/z-push/lib/core/interprocessdata.php(79): IpcSharedMemoryProvider->__construct()
#2 /usr/share/z-push/lib/core/topcollector.php(45): InterProcessData->__construct()
#3 /usr/share/z-push/lib/core/zpush.php(515): TopCollector->__construct()
#4 /usr/share/z-push/lib/core/devicemanager.php(86): ZPush::GetTopCollector()
#5 /usr/share/z-push/lib/core/zpush.php(487): DeviceManager->__construct()
#6 /usr/share/z-push/index.php(78): ZPush::GetDeviceManager()
#7 {main}
  thrown (1)

I searched some times in the internet and I found the following solution:
Change line 44 from:
ZLog::Write(LOGLEVEL_DEBUG, sprintf("%s(): Initialized mutexid %s and memid %s.", $class, $this->mutexid, $this->memid));

through:
ZLog::Write(LOGLEVEL_DEBUG, sprintf("%s(): Initialized %s and %s.", $class, $this->mutexid::class, $this->memid::class));

and it works. I've no idea why - I'm not able to understand the code, maybe it helps to solve the error
Have a great day
Helmut

**Comment by matidau** [comment]
Hi @Helmut1965, Can you check your installation I don't think you are using a 2.7.x version or the latest dev branch. I would recommend that you use the latest from https://github.com/Z-Hub/Z-Push/releases

**Comment by Helmut1965** [comment]
Please give a few days, I'll double check both case til next week Monday - thanks for response

**Comment by Helmut1965** [comment]
can be closed, was caused by a version mix. Sorry for the effort
Helmut

**Comment by Helmut1965** [comment]
can be closed, was caused by a version mix. Sorry for the effort
Helmut
