### ISSUE TITLE
Search not working in gmail apps andriod

### ISSUE THREAD

**Issue by chittaranjan870** [Z-Hub/Z-Push#114]
search not working  z-push-backend-imap (= 2.5.1-1). I am using cyrus Imap(Ver 3.0.13) server for mailbox. Everything is working fine except email search.

**Below WARN log found while searching...
[**androidc1310712648] Searchtype 'MAILBOX' is not supported.****

Anyone please help 

This is my z-push-backend-imap configuration
// best cross-platform compatibility (see http://php.net/imap_open for options)
//define('IMAP_OPTIONS', '/notls/norsh');
define('IMAP_OPTIONS', '/notls/norsh');

// Mark messages as read when moving to Trash.
//      BE AWARE that you will lose the unread flag, but some mail clients do this so the Trash folder doesn't get boldened
define('IMAP_AUTOSEEN_ON_DELETE', false);

// When configured set this to true to remove the error
define('IMAP_FOLDER_CONFIGURED', true);

// Folder prefix is the common part in your names (3, 4)
define('IMAP_FOLDER_PREFIX', 'INBOX');

// Inbox will have the preffix preppend (3 & 4 to true)
define('IMAP_FOLDER_PREFIX_IN_INBOX', false);

// Inbox folder name (case doesn't matter) - (empty in 4)
define('IMAP_FOLDER_INBOX', 'INBOX');

// Sent folder name (case doesn't matter)
define('IMAP_FOLDER_SENT', 'Sent');

// Draft folder name (case doesn't matter)
define('IMAP_FOLDER_DRAFT', 'Drafts');

// Trash folder name (case doesn't matter)
define('IMAP_FOLDER_TRASH', 'Trash');

// Spam folder name (case doesn't matter). Only showed as special by iOS devices
define('IMAP_FOLDER_SPAM', 'Junk');

// Archive folder name (case doesn't matter). Only showed as special by iOS devices
define('IMAP_FOLDER_ARCHIVE', 'Archive');

**Comment by matidau** [comment]
Is the rest of your mail on Android via Z-Push working, receiving and sending email?

Check your Z-Push config.php and if your using it, Combined Backend config.php.

That is the only search type that Imap supports. 

Also I mention that 2.5 isn't supported. You might be better off upgrading to the latest. 

Cheers,
Mat

**Comment by chittaranjan870** [comment]
Yes I am using combined backend.
Email send/receive also calendaring are working fine.
Only search not working.

Sould I upgrade z-push to 2.6 version or any configuration related issue need to be change, Please guide me

**Comment by matidau** [comment]
2.6 is also unsupported so you should look at making the jump to the latest 2.7.4
https://github.com/Z-Hub/Z-Push/releases

Also just to note that the minimum supported version of PHP is 7.4.

You should take a back up of your config files, and untar the release over the top of your existing.

Possibly backing up the entire Z-Push would be a good idea.

There are some config changes between 2.5 and 2.6, but I can't remember what to look out for.

**Comment by chittaranjan870** [comment]
I have upgraded to latest z-push 2.7.4 and PHP 8.3, but still issue is same.
Please find the log for reference.

**23/10/2024 15:15:54 [56928] [WARN] [ux1@domain.com] Searchtype 'MAILBOX' is not supported.**
23/10/2024 15:15:54 [56928] [ INFO] [ux1@domain.com] cmd='Search' memory='1.86 MiB/2.00 MiB' time='0.02s' devType='Android' devId='androidc1310712648' getUser='ux1@domain.com' from='192.168.10.152' idle='0s' version='2.7.4
' method='POST' httpcode='200'

**Comment by matidau** [comment]
Can you post your main and combined Backend config?

**Comment by chittaranjan870** [comment]
please find i have changed this field only and rest are keep  default
also enclosed file for your reference


 **main config**
	define('PROVISIONING', false);
	define('LOOSE_PROVISIONING', true);
	define('BACKEND_PROVIDER', 'BackendCombined');
	define('SEARCH_PROVIDER', 'BackendSearchLDAP');


**combined Backend config**
'backends' => array(
                'i' => array(
                    'name' => 'BackendIMAP',
                ),
              //  'z' => array(
              //    'name' => 'BackendKopano',
              //  ),
[combined_Backend_config.txt](https://github.com/user-attachments/files/17500263/combined_Backend_config.txt)
[z-push_main_config.txt](https://github.com/user-attachments/files/17500264/z-push_main_config.txt)

              //  'm' => array(
              //      'name' => 'BackendMaildir',
              //  ),
              //  'v' => array(
              //      'name' => 'BackendVCardDir',
              //  ),
                'l' => array(
                    'name' => 'BackendLDAP',
                ),
                'd' => array(
                    'name' => 'BackendCardDAV',
                ),
                'c' => array(
                    'name' => 'BackendCalDAV',
                ),
            ),
            'delimiter' => '/',

	'folderbackend' => array(
                SYNC_FOLDER_TYPE_INBOX => 'i',
                SYNC_FOLDER_TYPE_DRAFTS => 'i',
                SYNC_FOLDER_TYPE_WASTEBASKET => 'i',
                SYNC_FOLDER_TYPE_SENTMAIL => 'i',
                SYNC_FOLDER_TYPE_OUTBOX => 'i',
                SYNC_FOLDER_TYPE_TASK => 'c',
                SYNC_FOLDER_TYPE_APPOINTMENT => 'c',
                SYNC_FOLDER_TYPE_CONTACT => 'l',
                SYNC_FOLDER_TYPE_NOTE => 'c',
                SYNC_FOLDER_TYPE_JOURNAL => 'c',
                SYNC_FOLDER_TYPE_OTHER => 'i',
                SYNC_FOLDER_TYPE_USER_MAIL => 'i',
                SYNC_FOLDER_TYPE_USER_APPOINTMENT => 'c',
                SYNC_FOLDER_TYPE_USER_CONTACT => 'l',
                SYNC_FOLDER_TYPE_USER_TASK => 'c',
                SYNC_FOLDER_TYPE_USER_JOURNAL => 'c',
                SYNC_FOLDER_TYPE_USER_NOTE => 'c',
             // SYNC_FOLDER_TYPE_UNKNOWN => 'z',
            ),

**Comment by matidau** [comment]
MAILBOX is not a SearchType of ldap you should leave SEARCH_PROVIDER as the default.

**Comment by chittaranjan870** [comment]
Thanks, 
Yes  it works when I leave SEARCH_PROVIDER to default. But after set it default another issue is getting, that is 
**24/10/2024 12:21:58 [986008] [WARN] [ux1@domain.com] Searchtype 'GAL' is not supported.**

I means auto suggestion of address is not working while composing new mail.

**Comment by matidau** [comment]
Try setting your SYNC_FOLDER_TYPE_CONTACT and SYNC_FOLDER_TYPE_USER_CONTACT to carddav ('d')

Edit: alternatively you could use the searchldap Backend but you will need to add this to your Combined Backend config and configure the searchldap backend.

**Comment by chittaranjan870** [comment]
After set SYNC_FOLDER_TYPE_CONTACT and SYNC_FOLDER_TYPE_USER_CONTACT to carddav ('d') , now only saved contacts are appearing in compose box.
But I want to use ldap Global address book should appear in compose box.

I have already configured galsearch-ldap.conf.php with Combined Backend config,  but how to use it ?

**Comment by matidau** [comment]
If you have modified the combined Backend config it should be using ldap instead for carddav.

Note: my reading of the code is the Combined Backend only supports one Backend per type of search. If you are expecting to see both backends results you will need to solve this in your carddav or ldap server.

**Comment by chittaranjan870** [comment]
Okay, understand
That means z-push search mechanism reads only one at time (either Backend LDAP search or Backend IMAP search).


Thanks for your respond
