### ISSUE TITLE
Implement AS 16.0 support

### ISSUE THREAD

**Issue by nvsystems** [Z-Hub/Z-Push#15]
Recreation of bug https://jira.kopano.io/browse/ZP-713:

On the 14th of September 2015 MS published new AS documentation which has a new AS protocol version.
The changes include:
- enhanced calendar reliability
- attachments in calendar items
- syncing the drafts folder
Announcement: http://blogs.msdn.com/b/exchangedev/archive/2015/06/08/announcing-exchange-activesync-v16.aspx

ActiveSync 16 has been supported in iOS since iOS 9.x (September 2015).

For cool things that are now possible with recent ActiveSync versions you can check:
https://grommunio.com/de/neuigkeiten/integration-von-exchange-activesync-16/

**Comment by matidau** [comment]
Thanks for raising this issue. AS 16.0/.1 support is still on the roadmap.

**Comment by matidau** [comment]
Still need to work on the other backends AS16.1 support

**Comment by matidau** [comment]
Bit more progress on AS16.1.

Still need to Finish working on the IMAP Backend and drafts.

**Comment by matidau** [comment]
Still need to work on the Imap Backend import of drafts from the phone, and Kopano testing if that backend is still used. confident that we can release this for 2.8.0 in October
