### ISSUE TITLE
No build instructions or readme for z-push

### ISSUE THREAD

**Issue by Danrancan** [Z-Hub/Z-Push#17]
Could you please provide me with build instructions or a readme file with how to build this on Ubuntu 20.04? There is little documentation. Not sure why.

**Comment by matidau** [comment]
As mentioned in the discussions, Z-Push doesn't need to be built. There is a readme and it points to the installation instructions on the Wiki https://github.com/Z-Hub/Z-Push/wiki/Installation

The wiki is mostly a copy of the Kopano Z-Push Wiki, if you are using another backend this might not be as useful to you.

**Comment by JSDA123** [comment]
The instructions say use the repo, but the repo doesn't have 2.7.0.  Are there instructions on how to install from the source files posted here?

**Comment by matidau** [comment]
There isn't as yet. For my curiosity, are you using this with Kopano?

**Comment by JSDA123** [comment]
No I'm not using it with Kopano, just trying to install Z-Push 2.7.0 on Ubuntu 22.04. I have previously used the repository and deb files to install but not clear what to do with the source files provided.

**Comment by matidau** [comment]
I've updated the Wiki with some very general instructions to get the latest release and to clone from git https://github.com/Z-Hub/Z-Push/wiki/Installation#z-push-on-ubuntu-2204 

I've also opened up the wiki so all Github users can contribute, if you feel like sharing some of your knowledge.

**Comment by JSDA123** [comment]
Thank you, that helped. I now have it up and running for testing. 

I'm confused about the state directory, the config says it is at /var/lib/z-push but that location is where your instructions said to install the files from src, and I don't see states there.  Where are states stored now?  I'm running in a docker container and would like to persist that data.

Edit:  I found that if I copied src/ to /usr/share/z-push/ instead of /var/lib/z-push/, the state directory functions as expected at /var/lib/z-push. Additionally I did not have to modify the files at configs/apache2, just copied them to /etc/apache2/conf-available.  

So  /usr/share/z-push seems to be the better install location for Ubuntu.

Thanks again for your help.

**Comment by matidau** [comment]
No problems, glad it worked out.

The state machine doesn't get created until you you add in a user, it gets auto-created as needed. This might be why you didn't see the state machine when you expected to. 

For reference, the State Machine location is in the config.php
https://github.com/Z-Hub/Z-Push/blob/ca9e720b7bec33595bba64ed18924b8ef6aa5f4d/src/config.php#L71C1-L71C45
```
    define('STATE_MACHINE', 'FILE');
    define('STATE_DIR', '/var/lib/z-push/');
```

**Comment by matidau** [comment]
Hey @Danrancan 

These instructions should also work for Ubuntu 20.04 as long as PHP is 7.4 or 8.0+

https://github.com/Z-Hub/Z-Push/wiki/Installation#z-push-on-ubuntu-2204

Let me know if that solves your issue.

**Comment by matidau** [comment]
@JSDA123 

> Edit: I found that if I copied src/ to /usr/share/z-push/ instead of /var/lib/z-push/, the state directory functions as expected at /var/lib/z-push. Additionally I did not have to modify the files at configs/apache2, just copied them to /etc/apache2/conf-available.
> 
> So /usr/share/z-push seems to be the better install location for Ubuntu.

Sorry I missed what you were stating here first time round. I've updated the wiki to /usr/local/lib/z-push/. That was a typo when I made the entry.

**Comment by matidau** [comment]
Will close this issue off as no response from the original requester and believe that the wiki gives just enough to get started.
