### ISSUE TITLE
Fatal error with unsupported charset

### ISSUE THREAD

**Issue by michlann** [Z-Hub/Z-Push#26]
Hello,

I came upon a mail that seems to contain headers in charset `windows-874`. Since this charset is obviously unsupported by `mb_convert_encoding()`, I get the following fatal error:

```
23/08/2023 21:28:24 [1050936] [FATAL] [user@some.mail] Fatal error: /usr/share/z-push-2.7.0/lib/utils/utils.php:1281 - Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "windows-874" in /usr/share/z-push-2.7.0/lib/utils/utils.php:1281
Stack trace:
#0 /usr/share/z-push-2.7.0/lib/utils/utils.php(1281): mb_convert_encoding()
#1 /usr/share/z-push-2.7.0/lib/utils/utils.php(1407): Utils::convertRawHeader2Utf8()
#2 /usr/share/z-push-2.7.0/backend/imap/imap.php(1154): Utils::CheckAndFixEncodingInHeaders()
#3 /usr/share/z-push-2.7.0/lib/default/diffbackend/exportchangesdiff.php(160): BackendIMAP->GetMessage()
#4 /usr/share/z-push-2.7.0/lib/request/sync.php(1199): ExportChangesDiff->Synchronize()
#5 /usr/share/z-push-2.7.0/lib/request/sync.php(956): Sync->syncFolder()
#6 /usr/share/z-push-2.7.0/lib/request/requestprocessor.php(116): Sync->Handle()
#7 /usr/share/z-push-2.7.0/index.php(107): RequestProcessor::HandleRequest()
#8 {main}
  thrown (1)

```

While it might be difficult to support all existing charsets worldwide, a more resiliant approach might be good. A comment below the [list of supported encodings](https://www.php.net/manual/en/mbstring.supported-encodings.php) suggests using `mb_list_encodings()`  to check before calling the conversion function. That still leaves the question what to do if an unknown encoding is found. I don't have a good answer. Maybe there is a function to "safely" discard all non-ascii characters? Just as a last-resort?

Looking at lib/utils/utils.php(1281), i.e. the function that calls `mb_convert_encoding()`, there is already a special case for a Japanese encoding. Also, I don't get the logic behind the way the function is coded - it is passed a string argument to use for storing the converted string, but also returns a string value - or is that just my lacking PHP skills?

It seems I have successfully worked around my specific problem by aliasing windows-874 to ISO-8859-11 - which seems to work despite it not being listed as officially supported.

**Comment by matidau** [comment]
Heya,

It is likely that #21 will fix this but I will need to still test. If you would be willing to test this as well please let me know how you get on 😊

**Comment by michlann** [comment]
Good for now, thanks!
