### ISSUE TITLE
Make z-push.org an alias of z-push.github.io (or a redirect)

### ISSUE THREAD

**Issue by marclaporte** [Z-Hub/Z-Push#33]
https://z-push.github.io/ has the updates that https://z-push.org/ is missing.

**Comment by matidau** [comment]
Heya,

I've reached out to Kopano, will let you know if this is possible.

Cheers,
Mat

**Comment by fbartels** [comment]
z-push.org now directly maps to https://z-push.github.io/

**Comment by matidau** [comment]
Thanks Felix always appreciate your time for the project 🙂
