### ISSUE TITLE
PHP-MAPI extension is not available

### ISSUE THREAD

**Issue by Phyks** [Z-Hub/Z-Push#36]
Hi,

I am using Z-Push on a Debian bullseye server following the [wiki installation guide](https://github.com/Z-Hub/Z-Push/wiki/Installation). Z-Push is on top of a Dovecot server (localhost) and I am configuring it, in particular defining the backend as

```
$ cat /var/lib/z-push/config.php  | grep BACKEND_PROVIDER
    define('BACKEND_PROVIDER', 'BackendIMAP');
```

Whenever I configure a new device (iOS, also tested with https://testconnectivity.microsoft.com/tests/Eas/input), autodiscover does not work. I get the following output in the logs:

```
==> /var/log/z-push/autodiscover.log <==
20/11/2023 16:57:31 [2230113] [FATAL] [#unknown] Exception: (FatalMisconfigurationException) - PHP-MAPI extension is not available
20/11/2023 16:57:31 [2230113] [ERROR] [#unknown] Unable to complete autodiscover because of ZPushException. Error: PHP-MAPI extension is not available
```

PHP-MAPI extension does not seem to be available anywhere easily and AFAIK it should only be used by Kopano Backend. Not sure why it is blocking autodiscover with the following setup?

Thanks!

**Comment by matidau** [comment]
Hi Phyks,

You will also need to set the Backend in Autodiscover configure.php

https://github.com/Z-Hub/Z-Push/blob/144ecb788b2a79cfad3d21d2a59a6c5004967330/src/autodiscover/config.php#L110C12-L110C12

Cheers,
Mat

**Comment by Phyks** [comment]
I can confirm it works, I thought `config.php` at the root of this repo had precedence over any other `config.php` file in subdirectory.

Thanks!
