### ISSUE TITLE
I cannot sync from ios 16 or 17

### ISSUE THREAD

**Issue by matidau** [Z-Hub/Z-Push#43]
> No problems :)

hi matidau,
zpush 2.7.0, I cannot sync from ios 16 or 17, some log are retry to provisioning command, what can I do

_Originally posted by @cvhoangpt in https://github.com/matidau/Z-Push/issues/9#issuecomment-1883025798_

**Comment by matidau** [comment]
Hi @cvhoangpt

Can you post what's in the Z-Push logs, and let me know what Backend you are using?

Cheers,
Mat

**Comment by cvhoangpt** [comment]
> Hi @cvhoangpt
> 
> Can you post what's in the Z-Push logs, and let me know what Backend you are using?
> 
> Cheers, Mat

Hi Mat,
I use Backend Zimbra. So some iPhone load subject meta but when click on email, loading icon stucking so much.
_I provide some logs (z-push.log):_
`2024-01-09 10:59:28,475 INFO  [qtp1641313620-32086:https://***/service/soap/] [name=***@***.vn;mid=3479;ip=192.168.3.240;port=56904;ua=Outlook-iOS-Android/1.0(...0b914a) devip=192.168.2.251 ZPZB/71;soapId=5e2aafff;] soap - DestroyWaitSetRequest elapsed=2
2024-01-09 10:59:28,512 INFO  [qtp1641313620-32086:https://***/service/soap/] [name=***@***.vn;mid=3479;ip=192.168.3.240;port=56906;ua=Outlook-iOS-Android/1.0(...0b914a) devip=192.168.2.251 ZPZB/71;soapId=5e2ab000;] soap - CreateWaitSetRequest elapsed=2`

`[FATAL] [***] Exception: (ProvisioningRequiredException) - Retry after sending a PROVISION command
09/01/2024 10:54:51 [20559] [ INFO] [***] cmd='Settings' memory='9.97 MiB/10.25 MiB' time='0.14s' devType='iPhone' devId='j95cmdo6sh45veof6dm6j3futk' getUser='***' from='***' idle='0s' version='GIT' method='POST' httpcode='449'`

**Comment by matidau** [comment]
Is this a new install of Z-Push or was it working previously and recently stopped? 

Can you try testing with a new user that only has a couple of items in the mailbox, this is to rule out a problem with Zimbra or the Backend settings. 

Also changing the logging to WBXML might shed more light. https://github.com/Z-Hub/Z-Push/wiki/Debugging#how-to-enable-wbxml-logging

**Comment by cvhoangpt** [comment]
> Is this a new install of Z-Push or was it working previously and recently stopped?
> 
> Can you try testing with a new user that only has a couple of items in the mailbox, this is to rule out a problem with Zimbra or the Backend settings.
> 
> Also changing the logging to WBXML might shed more light. https://github.com/Z-Hub/Z-Push/wiki/Debugging#how-to-enable-wbxml-logging

In the past, I install z-push version 2.3.7 and it's working, so that version does not support ASV version 14 or 14.1
So I fully remove z-push old version and install 2.7.0 with guide [https://www.stefanseidel.info/Z-Push_on_Zimbra_8](url), Android (Gmail with Exchange) or Outlook for iOS, Outlook for Windows run OK.
When I try with new user (3-4 new email), mail for iOS load OK but when reload not working, email disapeared or load very slowly

**Comment by matidau** [comment]
> So I fully remove z-push old version and install 2.7.0 with guide [https://www.stefanseidel.info/Z-Push_on_Zimbra_8](url)

The configuration for /opt/z-push/config.php isn't correct from that guide. Please use the configuration here:
https://github.com/Z-Hub/Z-Push/wiki/Installation#configuration

If you are looking for a more recent guide please try this one:
https://imanudin.net/2023/10/07/exchange-activesync-for-zimbra-open-source-edition-nginx-custom/

If you're having further difficulties it might be a good idea to reach out to the Zimbra Backend project 
https://sourceforge.net/p/zimbrabackend/support-requests/

Edit:spelling

**Comment by cvhoangpt** [comment]
In new version, I config with new config you provide but iOS not working 👯

**Comment by cvhoangpt** [comment]
> If you are looking for a more recent guide please try this one: https://imanudin.net/2023/10/07/exchange-activesync-for-zimbra-open-source-edition-nginx-custom/
> 
OK I will try with this docs, thank you.

**Comment by cvhoangpt** [comment]
hi Mat, I have installed Z-Push with imanudin and it working, but when I sync in Outlook, it's will reload again with 0 email when I click Inbox. What wrong?

**Comment by matidau** [comment]
Hi @cvhoangpt

Have you reached out to the Zimbra Backend Project for support?

Cheers,
Mat

**Comment by cvhoangpt** [comment]
Hi @matidau 
That only happens with low-message emails. I think it's no problem.

**Comment by matidau** [comment]
No problems. Sounds like your original issue is resolved. Can we close this issue?

**Comment by cvhoangpt** [comment]
I think problem is performance of z-push, do you recommend for tunning z-push?

**Comment by matidau** [comment]
We don't have any guides on that, but from what I have seen it is Backend and Mail Server dependant. 

I feel like a broken record, but have you reached out to the Zimbra Backend Project?

Cheers,
Mat

Edit: spelling

**Comment by cvhoangpt** [comment]
Can you give me contact of supporter?

**Comment by matidau** [comment]
> If you're having further difficulties it might be a good idea to reach out to the Zimbra Backend project 
> https://sourceforge.net/p/zimbrabackend/support-requests/
> 

Provided earlier, see above.

**Comment by cvhoangpt** [comment]
Thank for your help. Have a great day. Now you can close this issue.

**Comment by matidau** [comment]
No problems 😊
