### ISSUE TITLE
Filter by user agent or DeviceType possible?

### ISSUE THREAD

**Issue by WEBudoGT** [Z-Hub/Z-Push#51]
Is it possible already to filter/reject connections from user-agent or device type information?
I'm asking this because we have some email clients that configure their Outlook with z-push's server information and we have a very basic server which can only handle some mobiles.
So we need to block those requests for them not to take the server resources.

Any ideas?
Thanks!

**Comment by matidau** [comment]
Hi Alex,

You can do this via nginx `if` or `map` directives. For Apache you can use mod_rewrite module.

Cheers,
Mat

**Comment by fbartels** [comment]
An example of such a block can be found in https://stackoverflow.com/a/22192426. Only needs to be adapted for the user agent that is used by the Outlook app.

**Comment by matidau** [comment]
Going to close this off now
