### ISSUE TITLE
KopanoBackend->GetKoeGabBackendFolderId() Found 0 entries in the store 'SYSTEM' matching the name 'Z-Push-KOE-GAB'

### ISSUE THREAD

**Issue by eugenefvdm** [Z-Hub/Z-Push#53]
**Describe the bug**
Numerous of our Kopano Community member's Kopano Systems are breaking down with the following message:

```bash
# tail -f /var/log/z-push/z-push-error.log
14/02/2024 10:28:03 [ 3169] [WARN] [user@example] KopanoBackend->GetKoeGabBackendFolderId() Found 0 entries in the store 'SYSTEM' matching the name 'Z-Push-KOE-GAB'.
```

We are 100% aware Kopano Community Edition has been discontinued and there is no more support. The problem is we have  many installations and we can't just tell the people that their software is not working anymore. We have to try and solve the problem.

I have Googled this extensively and on the now defunct Kopano Community Forum there is this post:
https://forum.kopano.io/topic/594/z-push-error

Here @fbartels refers to a Wiki entry that doesn't exist anymore, https://wiki.z-hub.io/display/ZP/Configuring+GAB-Sync+for+Kopano+OL+Extension

Please, we are desperate. It seems we need to put in a blank `USERNAME` somewhere but I can't find the exact location. 

Is this it? `/etc/z-push/config.php`

**To Reproduce**
1. Users informs that email is not synching into Outlook anymore. Often refresh in Outlook has to be pressed.
2. Install Kopano OLE extension from here: https://download.kopano.io/community/olextension%3A/
3. Choose Full Recync, Outlook Closes 
4. From here Outlook never works again. Message is "Waiting for server" and z-push log file repeats this message every split second.

**Comment by matidau** [comment]
Hi Eugene,

I think the Z-Hub wiki site was moved to the main kopano wiki site.

You can use the Internet archive to get the page you need.

https://web.archive.org/web/20230430011936/https://kb.kopano.io/display/ZP/Configuring%2BGAB-Sync%2Bfor%2BKopano%2BOL%2BExtension

Cheers,
Mat

Edit: also not sure what your installation source is or what version you are running, so there's a chance you don't have the necessary files installed. The current version is located here:
https://github.com/Z-Hub/Z-Push/tree/develop/tools/gab-sync

And will be available from any of the releases or tags to download:
https://github.com/Z-Hub/Z-Push/tags

**Comment by matidau** [comment]
> Users informs that email is not synching into Outlook anymore. Often refresh in Outlook has to be pressed.

What version of Outlook are they running? It might be related to https://github.com/Z-Hub/Z-Push/issues/52

**Comment by eugenefvdm** [comment]
@matidau thank you so much! 

You were right, this instantaneously solved the [issue](https://github.com/Z-Hub/Z-Push/issues/52):

```bash
"C:\Program Files\Common Files\microsoft shared\ClickToRun\officec2rclient.exe" /update user updatetoversion=16.0.17126.20132
```
