### ISSUE TITLE
Duplicate Pings from one client starting at the same second do not get terminated early

### ISSUE THREAD

**Issue by liverpoolfc-fan** [Z-Hub/Z-Push#55]
In testing activesync from the GMail client on Android I frequently observed that making a change to the status of an email (reading or marking it as unread) would generate 2 almost simultaneous new Ping requests to the server, making 3 in total for the client.

If the start timestamp (unix seconds since 1-1-1970) was different the z-push function DoForcePingTimeout() in pingtracking.php would cause the older one of the processes to self-terminate. This would cause the original Ping request to self-terminate at the end of it's current ping cycle. 

However, what I have observed is that because the two new Ping processes are starting so soon after each other the start timestamp on both of them is almost always the same. The existing logic does not tell one of the processes to stop.  

This leads to extra load on the z-push server and the backend server. 
 
I have been able to reproduce the condition easily. 

Vincent

**Comment by matidau** [comment]
Thanks for raising this and the PR. Will close this off now.
