### ISSUE TITLE
Z-Push do not work with Radicale CardDAV

### ISSUE THREAD

**Issue by rpc-scandinavia** [Z-Hub/Z-Push#67]
**Describe the issue**
I am setting up a system with Z-Push combined backend and Radicale CardDAV / CalDAV.
ActiveSync works okay with CalDAV, but CardDAV do not work.
I found this thread, where a (now deleted user) describes a solution:

[https://github.com/Kozea/Radicale/issues/386](https://github.com/Kozea/Radicale/issues/386)

In that thread, Ghost modifies the "z-push/include/z_carddav.php" file around line 660.
There he swapped the first two IF blocks:

``
	if (isset($response->propstat->prop->resourcetype->addressbook)) {
	// It's an addressbook
``

and

``
	if ((strlen($this->url_vcard_extension) > 0 && preg_match('/'.$this->url_vcard_extension.'/', $response->href) &&
	!(isset($response->propstat->prop->resourcetype) && isset($response->propstat->prop->resourcetype->addressbook)))
	|| preg_match('/vcard/', $response->propstat->prop->getcontenttype) || isset($response->propstat->prop->{'address-data'}) || isset($response->propstat->prop->{'addressbook-data'})) {
	// It's a vcard
``

so the "addressbook" condition/block comes first and the "vcard" condition/block comes second.

With this modification, Z-Push ActiveSync works with Radicale CardDAV  :-)

**To Reproduce**
1. Get a working Radicale CardDAV with contacts
2. Configure Z-Push to use combined backends and get addressbooks/contacts from CardDAV
3. Synchronize on device (I tried an iPhone 6+ and a LineageOS 20)
4. No contacts appears

**Expected behavior**
Contacts appears.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Z-Push 2.7.3
 - Radicale 3.2.0

**Comment by matidau** [comment]
Thanks for this @rpc-scandinavia

I can see that your ghost user was Powercommy, and that he raised it on the previous support forum. But I have no further info.

https://forum.kopano.io/topic/809/z-push-with-a-radicale-carddav-backend

As Z-Push works with other carddav providers, can you provide an example carddav XML response? and I should be able to quickly check the mentioned code block against it.

**Comment by rpc-scandinavia** [comment]
Sure @matidau, and thank you.

Request:
```
$ curl -u 'user:password' -X REPORT 'http://localhost:9000/rpc@rpc-scandinavia.dk/194fa3cd-6e0a-d681-7474-70dce65754d3' -H 'Depth: 1' -H 'Content-Type: application/xml' --data '<?xml version="1.0" encoding="UTF-8" ?>
<C:addressbook-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav">
  <D:prop>
    <D:getetag/>
    <C:address-data/>
  </D:prop>
</C:addressbook-query>'
```

Response:
```
<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:CR="urn:ietf:params:xml:ns:carddav"><response><href>/rpc%40rpc-scandinavia.dk/194fa3cd-6e0a-d681-7474-70dce65754d3/040000008200E00074C5B7101A82E00800000000806718EEF63BD801000000000000000001000000A275A1B6CC9A4368AEA4A9FF4ED9C5C9.vcf</href><propstat><prop><getetag>"673d7da82284693eda37c989b685596d379d8e1d22fac7f14cac7133f76b43c0"</getetag><CR:address-data>BEGIN:VCARD
VERSION:4.0
PRODID:-//Kopano//libicalmapi 11.0.2//EN
UID:040000008200E00074C5B7101A82E00800000000806718EEF63BD801000000000000000
 001000000A275A1B6CC9A4368AEA4A9FF4ED9C5C9
ADR;TYPE=HOME:;;Kongeveien 148, Xkjøping;Århus;;8000;DK
BDAY:1972-10-26T23:00:00Z
EMAIL;TYPE=INTERNET,PREF:test@test.dk
EMAIL;TYPE=INTERNET:test@test.no
FN:Test Håkon Testesen
N:Testesen;Test;Håkon;;
NOTE:This is a note that will not always import
ORG:NDK
REV:2024-05-15T22:33:01Z
TEL;TYPE=HOME:12 34 56 78
TEL;TYPE=MOBILE:23 45 67 89
TEL;TYPE=WORK:01 02 03 04
URL:https://itdd.dk/
END:VCARD
</CR:address-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>
```

**Comment by matidau** [comment]
Thanks, 

I don't see the resource type in the response, and it is likely that the Backend is requesting multiple different responses.

I'm working on a couple of other things at the moment, will look at this in the future.

Cheers,
Mat

**Comment by rpc-scandinavia** [comment]
Ok.
I did the same, but for a calendar.

But I see `<CR:address-data>` and `<C:calendar-data>`, plus the `.vcf` or `.ics` in the Response `href` tag. Some of that should identify the data type. However I do not know if this is standard DAV.

Request:
```
$ curl -u 'user:password' -X REPORT 'http://localhost:9000/rpc@rpc-scandinavia.dk/5bfcd4b0-819d-eca2-6535-29fe8a535b40' -H 'Depth: 1' -H 'Content-Type: application/xml' --data '<?xml version="1.0" encoding="UTF-8" ?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <D:getetag/>
    <C:calendar-data/>
  </D:prop>
</C:calendar-query>'
```

Response:
```
<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><response><href>/rpc%40rpc-scandinavia.dk/5bfcd4b0-819d-eca2-6535-29fe8a535b40/U9c811%3A679d5950ce0048dcae05367e0c403bb7003b04000000.ics</href><propstat><prop><getetag>"f2815a73b6291e32f35e65278436d5f87fd951cad1ba7ac02228c35a8c006b8f"</getetag><C:calendar-data>BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PYVOBJECT//NONSGML Version 1//EN
...
...
...
END:VEVENT
END:VCALENDAR
</C:calendar-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>
```

**Comment by matidau** [comment]
I've tracked this down to the addressbook collection response `xml->response->propstat->prop->resourcetype->addressbook` has the contenttype set to text/vcard `xml->response->propstat->prop->getcontenttype`

Other DAV servers have this set to application/octet-stream.

This should probably be addressed in Radicale.

**Comment by pbiering** [comment]
> Other DAV servers have this set to application/octet-stream.

Can you please lookup what is defined in RFC? Switching unconditionally the content-type can break other clients by accidents.

But to cover support, can you create a PR which is able to conditionally switch the content-type based on a global option (at least for testing) and user-agent?
