### ISSUE TITLE
Requires: php-mapi-webapp

### ISSUE THREAD

**Issue by aaabbb-123** [Z-Hub/Z-Push#87]
yum install z-push-common z-push-config-apache z-push-backend-kopano z-push-ipc-sharedmemory
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Resolving Dependencies
--> Running transaction check
---> Package z-push-backend-kopano.noarch 0:2.6.4+0-132.1 will be installed
--> Processing Dependency: php-mapi-webapp for package: z-push-backend-kopano-2.6.4+0-132.1.noarch
---> Package z-push-common.noarch 0:2.6.4+0-132.1 will be installed
--> Processing Dependency: php-mbstring for package: z-push-common-2.6.4+0-132.1.noarch
--> Processing Dependency: php-process for package: z-push-common-2.6.4+0-132.1.noarch
--> Processing Dependency: php-soap for package: z-push-common-2.6.4+0-132.1.noarch
---> Package z-push-config-apache.noarch 0:2.6.4+0-132.1 will be installed
---> Package z-push-ipc-sharedmemory.noarch 0:2.6.4+0-132.1 will be installed
--> Processing Dependency: php-pcntl for package: z-push-ipc-sharedmemory-2.6.4+0-132.1.noarch
--> Running transaction check
---> Package php-cli.x86_64 0:5.4.16-48.el7 will be installed
---> Package php-mbstring.x86_64 0:5.4.16-48.el7 will be installed
---> Package php-process.x86_64 0:5.4.16-48.el7 will be installed
---> Package php-soap.x86_64 0:5.4.16-48.el7 will be installed
---> Package z-push-backend-kopano.noarch 0:2.6.4+0-132.1 will be installed
--> Processing Dependency: php-mapi-webapp for package: z-push-backend-kopano-2.6.4+0-132.1.noarch
--> Finished Dependency Resolution
Error: Package: z-push-backend-kopano-2.6.4+0-132.1.noarch (z-push)
           Requires: php-mapi-webapp
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by matidau** [comment]
Heya, If you are using the https://download.kopano.io/ z-push sources you will need to search for the dependancies there.

I have used the script from https://github.com/thctlo/Kopano to install Kopano + Z-Push from packages, this may provide some hints for what you need.
