### ISSUE TITLE
Lack testing of emails using PGP and S/MIME encryption.

### ISSUE THREAD

**Issue by dallaslu** [Z-Hub/Z-Push#88]
Mainly derived from mimeDecode.php. it seems its not finished supporting encrypted emails.

Currently, in 2.7.3, errors are often encountered that prevent synchronization:

> 23/07/2024 01:18:47 [435106] [WARN] [u@test.com] /usr/local/lib/z-push/include/mimeDecode.php:347 Undefined array key 1 (2)
> 23/07/2024 01:18:47 [435106] [WARN] [u@test.com] /usr/local/lib/z-push/backend/imap/imap.php:1453 Undefined array key 0 (2)
> 23/07/2024 01:18:47 [435106] [WARN] u@test.com] /usr/local/lib/z-push/backend/imap/imap.php:1453 Undefined array key 1 (2)
> 23/07/2024 01:18:47 [435106] [WARN] [u@test.com] /usr/local/lib/z-push/backend/imap/imap.php:1453 Undefined array key 2 (2)
> 23/07/2024 01:18:47 [445311] [WARN] u@test.com] Mobile loop detected! Messages sent to the mobile will be restricted to 1 items in order to identify the conflict

**Comment by matidau** [comment]
Hi @dallaslu

More than likely this is a PHP8.x related error, but I can't confirm how complete it may be as I haven't done any PGP testing. I don't use PGP myself.

If you want to fully test before a release is done, I suggest you test against the develop branch.

Also happy for you to submit any PRs around this.

Cheers,
Mat

**Comment by dallaslu** [comment]
There are some confusing aspects of these places. While I don't know the details of the technical standards involved in this section, it smells bad.

The processing in this case is not in the same format as the `$return->parts` produced by the other cases. There's a break here, but there's another branch definition for the same case later.

`/src/include/mimeDecode.php` line 344:

```php
 case 'multipart/signed': // PGP
    $parts = $this->_boundarySplit($body, $content_type['other']['boundary'], true);
    $return->parts['msg_body'] = $parts[0];
    list($part_header, $part_body) = $this->_splitBodyHeader($parts[1]);
    $return->parts['sig_hdr'] = $part_header;
    $return->parts['sig_body'] = $part_body;
    break;
```

Here, the index is used instead of the key to loop through the `$mparts`.

`backend/imap/imap.php` line 1455:
```php
for ($i=0; $i < count($mparts); $i++) {
     $part = $mparts[$i];
```
