### ISSUE TITLE
iPhone loses sync between upgrades

### ISSUE THREAD

**Issue by matidau** [Z-Hub/Z-Push#92]
**Describe the bug**
iPhone loses sync between upgrades

https://discourse.mailinabox.email/t/problems-with-z-push-mail-sync-after-each-upgrade-of-miab/12145

**Expected behavior**
Exchange account on iPhone shouldn't be deleted and re-added. 

**Logs**
https://discourse.mailinabox.email/t/problems-with-z-push-mail-sync-after-each-upgrade-of-miab/12145/4

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - PHP Version: 8.0
 - Backend for: Mail-in-a-Box
 - and Version: v69

**Smartphone (please complete the following information):**
 - Device: iPhone6

**Comment by matidau** [comment]
Reviewed and messaged user

**Comment by smartperson** [comment]
@matidau I just upgraded to v70 of Mail in a Box from v69b and I've also run into this issue. Let me know if there's any additional information I could gather that would help.

**Comment by matidau** [comment]
Hi @smartperson

If you have set up the account again, Can I get you to run sudo z-push-admin -a fixstates and post the output? 

Do you have any error messages in the Z-Push error logs? 

FYI, To stop fixstates causing issues between Z-push upgrades I’ve raised this PR https://github.com/mail-in-a-box/mailinabox/pull/2432

Cheers,
mat

**Comment by eberproducts** [comment]
Hi Mat,
here is my output (in addition) to smartperson - in case you need it...


Validating and fixing states (this can take some time):
	11:08:26 Checking username casings: Processed: 6 - Converted: 0 - Removed: 0
	11:08:26 Checking available devicedata & user linking: Processed: 6 - Fixed: 0
	11:08:26 Checking for unreferenced (obsolete) state files: Processed: 1123 - Deleted: 7
	11:08:26 Checking for hierarchy folder data state: Devices: 4 - Processed: 6 - Fixed: 0 - Device+User without hierarchy: 0
	11:08:26 Checking flags of shared folders: Devices: 4 - Devices with additional folders: 0 - Fixed: 0

Cheers Wolfi

**Comment by matidau** [comment]
Thanks Wolfi,

Can you confirm if your iPhone lost sync after running fixstates?

Cheers,
Mat

**Comment by eberproducts** [comment]
Yes i can confirm this - just checked twice - eachtime after running fixstates the sync was lost and i had to re-setup the account on the iPhone.
